# Generated by Django 2.1.5 on 2019-01-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='delta_vix',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updates',
            name='delta_yield',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
